FROM python:3.6

RUN pip install --upgrade pip
RUN pip install --no-cache-dir  grpcio
RUN pip install --no-cache-dir  grpcio-tools
RUN pip install --no-cache-dir  pycurl
RUN pip install --no-cache-dir  requests

ADD app/grpc_server.py /app/grpc_server.py
ADD app/analysis_pb2.py app/analysis_pb2.py
ADD app/analysis_pb2_grpc.py app/analysis_pb2_grpc.py

COPY app/docker-entrypoint.sh /usr/local/bin/

EXPOSE 80

ENTRYPOINT ["docker-entrypoint.sh"]

