FROM python:3.6


ADD app/grpc_server.py /app/grpc_server.py
ADD app/analysis_pb2.py app/analysis_pb2.py
ADD app/analysis_pb2_grpc.py /app/analysis_pb2_grpc.py
ADD app/requirements.txt /app/requirements.txt


COPY app/docker_entrypoint_server.sh /usr/local/bin/

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 80

ENTRYPOINT ["docker_entrypoint_server.sh"]

